name: dift
channels:
  - xformers
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2023.5.7=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=39.0.1=py310h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.24.3=py310h5f9d8c6_1
  - numpy-base=1.24.3=py310hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - pillow=9.4.0=py310h6a678d5_0
  - pip=23.0.1=py310h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.9=h7a1cb2a_2
  - pytorch=1.13.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py310h06a4308_0
  - setuptools=67.8.0=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.1=py310_cu117
  - torchvision=0.14.1=py310_cu117
  - typing_extensions=4.5.0=py310h06a4308_0
  - urllib3=1.26.15=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - xformers=0.0.20=py310_cu11.7.1_pyt1.13.1
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - accelerate==0.19.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anyio==3.7.0
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-lru==2.0.2
      - async-timeout==4.0.2
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.0.0
      - brotli==1.0.9
      - cmake==3.26.3
      - comm==0.1.3
      - contourpy==1.0.7
      - cycler==0.11.0
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.15.0
      - exceptiongroup==1.1.1
      - executing==1.2.0
      - fastjsonschema==2.17.1
      - filelock==3.12.0
      - fonttools==4.39.4
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - gevent==22.10.2
      - geventhttpclient==2.0.2
      - greenlet==2.0.2
      - grpcio==1.54.2
      - huggingface-hub==0.14.1
      - imageio==2.33.0
      - importlib-metadata==6.6.0
      - ipykernel==6.23.1
      - ipympl==0.9.3
      - ipython==8.13.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - json5==0.9.14
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-lsp==2.2.0
      - jupyter-server==2.6.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.0
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.22.1
      - jupyterlab-widgets==3.0.7
      - kiwisolver==1.4.4
      - lazy-loader==0.3
      - lit==16.0.5
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mistune==2.0.5
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==3.2.1
      - notebook-shim==0.2.3
      - opencv-python==4.8.1.78
      - overrides==7.3.1
      - packaging==23.1
      - pandas==2.1.4
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.5.1
      - prometheus-client==0.17.0
      - prompt-toolkit==3.0.38
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - python-rapidjson==1.10
      - pytz==2023.3.post1
      - pyyaml==6.0
      - pyzmq==25.1.0
      - regex==2023.5.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - scikit-image==0.22.0
      - scipy==1.11.4
      - send2trash==1.8.2
      - sh==1.14.3
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - terminado==0.17.1
      - tifffile==2023.9.26
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - tomli==2.0.1
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.29.2
      - triton==2.0.0.post1
      - tritonclient==2.33.0
      - typing-inspect==0.6.0
      - tzdata==2023.3
      - uri-template==1.2.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.5.2
      - widgetsnbextension==4.0.7
      - wrapt==1.15.0
      - yarl==1.9.2
      - zipp==3.15.0
      - zope-event==4.6
      - zope-interface==6.0